### ISSUE TITLE
Gem is Out of Date

### ISSUE THREAD

**Issue by waltz** [jasmine/jasmine-ajax#118]
I'm in the process of migrating a project to use Jasmine. We want to use this package via RubyGems. It looks like there isn't a Gemspec file anymore and the version that's up on [RubyGems.org](https://rubygems.org/gems/jasmine-ajax) is pretty out of date.

* What happened?
* What's the recommended way to include this package?
* Are there plans to re-gemify this?
* Would you accept PR's to re-gemify this?

Thanks! This utility is overall fantastic and super well built. I appreciate the contribution a ton.

**Comment by slackersoft** [comment]
This package has never officially been released as a gem. The gem you linked to, was released by someone else.

The current ways to include jasmine-ajax into your project are:

* Use the [npm package](https://npmjs.org/jasmine-ajax)
* Use the [bower package](http://bower.io/search/?q=jasmine-ajax)
* In rails, you can use [rails assets](https://rails-assets.org/) to serve assets from the bower package
* Download the [mock-ajax.js](https://github.com/jasmine/jasmine-ajax/blob/master/lib/mock-ajax.js) file directly from the repo.

Since these options seem like they should cover most cases (rails-assets is probably what you want for your use-case), we don't have any plans to add more ways to release jasmine-ajax right now.

**Comment by waltz** [comment]
Thanks for the reply! Thanks for clarifying how the existing Gem related to
this repo.

I'm going to switch to using the RailsAssets version. That seems like the
lowest friction option for our project.

**Comment by slackersoft** [comment]
Cool, closing this.
