### ISSUE TITLE
get parameters not populated in data()

### ISSUE THREAD

**Issue by vishnukarthikl** [jasmine/jasmine-ajax#161]
I am using jasmine-ajax to mock $.ajax get calls. In my actual code I send some parameters through the data options.
````javascript
var request = $.ajax("/users", {
      data: {id:"1"},
});
````
but in my tests `jasmine.Ajax.requests.mostRecent().url` returns `/users?id=1` and `jasmine.Ajax.requests.mostRecent().data()` returns `{}`. Is there a way to make the url return /users and data return `{id:"1"}` to make my testing life easier?

**Comment by slackersoft** [comment]
Unfortunately, I think jQuery is messing with you a bit here because it will convert your `data` into the proper query params for a `GET` request.

Jasmine-Ajax saves off the actual `data` param passed to the `XmlHTTPRequest`s `send` function, and that is what we process to return back in the `data()` function. So if the info you want is in the query string it's there before jasmine-ajax gets ahold of it and we don't really have any way to know how you got it there.

Closing this since there's not much we can do. Thanks for using Jasmine!
