### ISSUE TITLE
ReferenceError: getJasmineRequireObj is not defined

### ISSUE THREAD

**Issue by smoholkar** [jasmine/jasmine-ajax#178]
Updating to jest 21.2.1 gives `ReferenceError: getJasmineRequireObj is not defined` . 

Any version above jest 19.0.1 gives me that error. Jest has nothing to do with jasmine-ajax. I also tried importing jasmine-core but still get this error. I'm not sure why.

**Comment by sgravrock** [comment]
Were you relying on Jest to make jasmine-ajax available? Jest 20 and later are no longer based on Jasmine. You might still be able to use jasmine-ajax with Jest >= 20, but you'll have to import it yourself.

**Comment by smoholkar** [comment]
I am not relying on jest to make jasmine-ajax available. I have jasmine-ajax imported and have been using the install, request etc  methods for my tests for a while.

**Comment by jkelly-haib** [comment]
You should be able to define `getJasmineRequireObj` globally:
```
require("jasmine");
var JasmineCore = require("jasmine-core");
global.getJasmineRequireObj = function() {
    return JasmineCore;
};
require("jasmine-ajax");
```

**Comment by slackersoft** [comment]
At this point, Jasmine-Ajax assumes it has a full-fledged Jasmine Core loaded and running in the same context that it is. If a newer Jest version isn't really loading a Jasmine anymore, you'll probably need to do something like @jkelly-haib suggests and load it yourself.

I'm going to close this, since it sounds more like an issue with Jest that Jasmine/Jasmine-Ajax. Hope this helps. Thanks for using Jasmine!
