### ISSUE TITLE
Disable access to jasmine props outside test case

### ISSUE THREAD

**Issue by garygreen** [jasmine/jasmine-ajax#190]
It's a bit strange that you can access things like `responseHeaders` inside the fake XHR outside your tests.. if you did use that in production code, you would think everything is fine because all tests are passing. But when you go to use a real browser, you don't have access to `responseHeaders` or other special props jasmine uses.

Would it be an idea to somehow "block" (or at least throw a warning) when accessing those props unless your within the confines of a test case? I'm not sure how feasible something like that is but it would help provide improved confidence your accessing properties that are on a true XHR object and will therefore work exactly like it should in a browser.

**Comment by slackersoft** [comment]
This is something we've thought about doing before, but it will take some work to really _hide_ the things that aren't on the public interface. The failure mode for this should be pretty obvious when running the live app, so it hasn't gotten prioritized for work. Another option might just be to rename things to have a leading underscore (`_`) to indicate privateness and make it more obvious that this probably isn't right.

Truly hiding the properties would make them unavailable for assertions inside your tests, so that might not be desirable for some things. I would be happy to review a pull request that makes it harder to accidentally use testing attributes in live code, but shrinking or changing the public interface for Jasmine-Ajax will probably have to wait until a major release.

Hope this helps. Thanks for using Jasmine!

**Comment by sgravrock** [comment]
Closing due to sustained lack of user interest.
