### ISSUE TITLE
require('jasmine-ajax') fails with erro 'window is not defined' 

### ISSUE THREAD

**Issue by abshkjha** [jasmine/jasmine-ajax#192]
I found that 'require('jasmine-ajax')' fails on node prompt with following error:

```
> require('jasmine-ajax')
ReferenceError: window is not defined
    at C:\Developer\SYSCHGM-1046\system-change\dms\ui\node_modules\jasmine-ajax\lib\mock-ajax.js:43:9
    at Object.<anonymous> (C:\Developer\SYSCHGM-1046\system-change\dms\ui\node_modules\jasmine-ajax\lib\mock-ajax.js:45:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
I have installed jasmin-ajax(3.4.0) and using jasmine(3.2.0), jasmine-core(3.2.1).
Node version is 8.11.4

Is there something I am missing, When I tried the same in e2e tests, test failed with same error.

**Comment by slackersoft** [comment]
Jasmine-Ajax attempts to replace the `XMLHttpRequest` constructor in the environment, and expects to be doing so in a browser. Because of this, Jasmine-Ajax doesn't do as much environment checking about whether to use `global` or `window` or something else entirely. Assuming that something in your code is making a call to `new XMLHttpRequest()`, it seems likely that these tests also might not work, even without Jasmine-Ajax.

I would be happy to review a pull request to document how to set up a virtual `window` in a Node.js context to allow use of Jasmine-Ajax.

**Comment by sgravrock** [comment]
I'm closing this due to prolonged lack of user interest.

We haven't seen any signs of interest in using Node to test code that calls XMLHttpRequest since 2018, and it appears to have been a fairly niche scenario even then. Anyone who's still in that situation and doesn't want to migrate to a more easily tested API like fetch can use jasmine-ajax 3.3.0.

**Comment by drax-db** [comment]
Yillar sonra babalik hissini anladiginda bile aklinda bir soru isareti olmasi ve bunun gercek olmasi hah :d
