### ISSUE TITLE
Close all requests on uninstall

### ISSUE THREAD

**Issue by GCorbel** [jasmine/jasmine-ajax#194]
## Expected Behavior

When Jasmine Ajax is uninstalled, with `jasmine.Ajax.uninstall()`, I think all pending should be released (executed) or aborted. Maybe we should be able to access to requests individually with `jasmine.Ajax.requests[index].abort()`.

## Current Behavior
With jQuery, `$.active` is kept along specs, even after `jasmine.Ajax.uninstall`. Requests are always active and doesn't trigger fail or done callbacks.

## Possible Solution
I tried to do : 

```
$.each(jasmine.Ajax.requests.filter(new RegEx('')), function (_, request) {
  request.abort();
});
```

It doesn't work. The real ajax requests doesn't seems be the same.

I propose to have functions `jasmine.Ajax.requests.abortAll()` and `jasmine.Ajax.requests.passThrough()` or abort requests individually.

## Suite that reproduces the behavior (for bugs)

This is a very simplified example of what I have : 

```javascript
describe("sample", function() {
  it('does not update $.active', function(done) {
    // with jQuery
    jasmine.Ajax.install();
    $.get('/assets.js');
    jasmine.Ajax.uninstall();
    code = function() {
      if ($.active === 0) {
        done(); // never reached
      } else {
        setTimeout(code, 500);
      }
    }
    setTimeout(code, 500);
  });

  it('does not trigger fail or done', function(done) {
    var request;
    var callSomething = function() {
      if (!request) {
        request = $.get('/assets.js').done(function() {
          request = null;
        }).fail(function() {
          request = null;
        });
      }

      return request;
    }

    jasmine.Ajax.install();
    callSomething()
    console.log(jasmine.Ajax.requests.first() == request); // Gives false
    jasmine.Ajax.uninstall();

    callSomething().done(function() {
      done();
    });
  });
});
```
## Context

The code ahead is just an example but active requests persists across specs. `$.active` keeps growing. Some parts of the application I'm working have functions where we cache requests to load some file only once.

## Your Environment

* Version used: 3.4.0
* Environment name and version: Chrome 71
* Operating System and version: The Docker image `ruby:2.5.3`

**Comment by slackersoft** [comment]
I'm hesitant to change the default behavior for uninstall because doing anything to the requests will cause any registered callback to be invoked at that time which could lead to strange behavior in some suites.

If you want to run through the list of stored requests, you should use the `at()` function instead of indexing with `[]`, since `jasmine.Ajax.requests` isn't the raw array of requests, but a wrapper object around them.

I would be happy to review a pull request to add an option to `uninstall` to do some work for all requests that are known. This could either be as some kind of known uninstall strategy, or as an optional callback that is invoked for each request. If it's a built-in strategy, Jasmine-Ajax will need to handle requests that are in all states:

```
UNSENT: 0,
OPENED: 1,
HEADERS_RECEIVED: 2,
LOADING: 3,
DONE: 4
```

**Comment by sgravrock** [comment]
Closing due to sustained lack of user interest.
