### ISSUE TITLE
Incompatible with Rails 6/Webpacker

### ISSUE THREAD

**Issue by amilligan** [jasmine/jasmine-ajax#197]
Similar to the issues I referenced in https://github.com/jasmine/jasmine/pull/1766, jasmine-ajax has grown over the years to include a mish-mash of dependencies on global state (e.g. jasmine) and passing values by polluting global state.

Since webpack has some fairly strong opinions about the pollution of global state, it pretty much breaks the library entirely.  I spent some time looking at how to make this webpack friendly, and to generally have a light a footprint as possible.  The result is at https://github.com/buildgroundwork/jasmine-ajax.

I made a number of changes, the latter of which are largely for partially restoring own sanity after unwinding the various levels of indirection.  Don't be deterred by the large changeset; most of the global state and webpack-specific changes are in the first few commits.

Taken as a whole, the result is that I
- Made it work with webpack.
- Removed dependence on any jasmine globals, including jasmine itself.  The #install method now takes a reference to jasmine.
- Eliminated as much pollution of global state as possible.  In an environment that provides `module.exports` there should be nothing added to global state.  In other environments the `mockAjaxRequires` object has to live on the global object.

I appreciate that many of the commits are not specifically to address webpack; after ten years the code was just long overdue for a deep cleanliness/simplification/consistency pass.  I also added a more aggressive .jshintrc file.  

I'm happy to discuss how to break this into manageable chunks, for reintegration back into the mothership.  I have **not** yet updated the README for the project, which I need to do since a couple changes I made did change the interface (e.g. passing jasmine to the `#install` method, not adding the resulting `MockAjax` object to `jasmine`).  I update the version to 5.0.x to reflect that the breaking changes.

Enjoy.

@slackersoft

**Comment by amilligan** [comment]
I've made some tweaks to the documentation.

**Comment by sgravrock** [comment]
Thank you for the contribution. Unfortunately, I don't think it's a good idea to take on breaking changes for this. In today's world of more easily mocked AJAX APIs, I suspect that jasmine-ajax is mainly used by people with older codebases that use XHR directly. I see continuing NPM downloads but no other sign of user engagement since 2019. That strongly suggests that few people are adding jasmine-ajax to new projects these days. We've probably reached the point where a new major release wouldn't see enough adoption to be worth the effort.
